# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-state-storage123"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "test/eu-central-1/stage/bacc/terraform.tfstate"
    region         = "eu-central-1"
  }
}
